### ISSUE TITLE
unit tests failing

### ISSUE THREAD

**Issue by madhugilla** [gvlproject/cloudbridge#30] opened 2017-03-07 12:25 UTC
Hi Guys,

cloned the repo on my windows workstation, ran tox (only python 2.7) and saw that 42 out of the 85 tests failed, is there any extra setup that i have to do to have all the tests pass ?

Attached is the testresults file.
[testresults.txt](https://github.com/gvlproject/cloudbridge/files/824339/testresults.txt)

Thanks

**Comment by nuwang** [comment] 2017-03-07 12:46
Hi, before you can run the tests, you need to set some environment variables pointing to the connection information/credentials for each supported cloud. As detailed in the log, the tests fail because the credentials for openstack are absent.
If you do not have access to a particular cloud, you can either run the mock tests or restrict the tests to AWS only, by setting the CB_TEST_PROVIDER instance variable.
See the following section for info on running the tests:
http://cloudbridge.readthedocs.io/en/latest/topics/testing.html

**Comment by nuwang** [comment] 2017-03-07 12:51
Just an additional note, there are two tests that currently fail on the dev branch due to an issue with a downstream library (moto), but apart from those, all other tests should pass.

I'll close this issue for now. Feel free to reopen if you run into any more trouble.

**Comment by madhugilla** [comment] 2017-03-07 13:47
On a side note, i am running WINDOWS, do i have to change any other configuration in the tox file ?

Thanks

**Comment by nuwang** [comment] 2017-03-07 13:50
There's nothing platform specific and all dependent libraries are windows compatible afaik. Nevertheless, we haven't tested on windows, so it'd be great to hear about your experience.

**Comment by madhugilla** [comment] 2017-03-07 16:51
In windows  we used the 'set' command to set both the provider and mock environment variables to aws and Yes and ran the tests we are still running into the same issue, attached is the same.
[testrun.txt](https://github.com/gvlproject/cloudbridge/files/825121/testrun.txt)

**Comment by nuwang** [comment] 2017-03-07 18:13
if you do
set CB_TEST_PROVIDER=aws
set CB_USE_MOCK_PROVIDERS=true
that should be sufficient. Two tests will fail because of the issue I mentioned before with the mock library (moto).

The test log you provided indicates that the above variables have not been set (which is why the OpenStack tests are running. When you set the above, only the aws tests should run).

**Comment by nuwang** [comment] 2017-03-07 18:54
We did notice that there was an error with regard to CR/LF encoding that typically occurs when moving between Windows and Unix, so this is a great opportunity to squash that issue. We're putting in a fix now by re-encoding this file. https://d168wakzal7fp0.cloudfront.net/aws_instance_data.json
It should be updated shortly.

Let us know how you go, we're keen to know whether that fixes that issue.

**Comment by afgane** [comment] 2017-03-07 19:08
Just updated the CloudFront distribution so that hopefully fixes the json encoding issue. Please let us know either way.

**Comment by madhugilla** [comment] 2017-03-08 06:14
Hi

1) Got the latest from the master
2) We ran on both Linux and windows and both of them have the same results 47 ran and 11 failures, attached are the test logs for the same.
3) Are we missing any dependencies ??

[windowstestruns.txt](https://github.com/gvlproject/cloudbridge/files/826768/windowstestruns.txt)
[linuxtestrun.txt](https://github.com/gvlproject/cloudbridge/files/826769/linuxtestrun.txt)

Thanks

**Comment by nuwang** [comment] 2017-03-08 06:22
I'm rerunning the Travis build: https://travis-ci.org/gvlproject/cloudbridge
Will get back to you once it finished. I'll also try it out on a Windows machine. So am I correct in assuming that the following steps will reproduce it?
1. Create Windows virtualenv
2. Install requirements
3. set CB_TEST_PROVIDER=aws and set CB_USE_MOCK_PROVIDERS=True
4. run tox -e py27

**Comment by madhugilla** [comment] 2017-03-08 06:25
we don't do the 1 and 2, we only run the 3 and 4 steps.

are 1 and 2 a must ??

**Comment by nuwang** [comment] 2017-03-08 06:29
Tox will create its own virtual environment, so you're right, it's not required. Usually, I tend to start off by creating a venv, which is why I put that in. Also, how are you planning to work with cloudbridge? Are you trying to develop with cloudbridge or contribute to cloudbridge?

**Comment by madhugilla** [comment] 2017-03-08 07:55
yes, we want to use cloud-bridge for interfacing, and if possible  certainly contribute down the line..

**Comment by nuwang** [comment] 2017-03-08 19:16
Thanks for reporting this, there was a minor issue which was causing problems - a missing double quote. It has since been fixed in this commit: https://github.com/gvlproject/cloudbridge/commit/7a235ea0cc1d1f4c1ebd552ba9b92d16b84160bc

Please try now and let us know - 2 tests may fail, but these only fail with the mock service, and pass on the actual cloud providers, so they are not functionally impacting.

Also, you can do a `pip install cloudbridge`, which may make life easier. @afgane will push out a new release with these fixed included sometime today.

**Comment by madhugilla** [comment] 2017-03-09 06:19
Hi,


1) When we run the tests for only AWS 2 tests fail
2) When we run all the tests we have 28 failing , 26 for open-stack and 2 for aws i am assuming we need an environment for open stack as it does not have a mocking support.

The above applies for both windows and Linux

[alltests.txt](https://github.com/gvlproject/cloudbridge/files/829932/alltests.txt)
[onlyaws.txt](https://github.com/gvlproject/cloudbridge/files/829933/onlyaws.txt)

Thanks

**Comment by nuwang** [comment] 2017-03-09 06:29
That's correct - the OpenStack tests must be run against real infrastructure, and therefore, you would need credentials. However, the Travis tests are run against real infrastructure, and all OpenStack tests pass: https://travis-ci.org/gvlproject/cloudbridge/jobs/209078842

Since you're only planning to use cloudbridge though, you shouldn't need to worry about this in principle, because the idea is that the testing is done centrally for cloudbridge, and someone using cloudbridge needs to only test against one infrastructure, and it should in principle, run on the other without further testing.

Was there a particular reason you wanted to run the tests in the first place?

**Comment by madhugilla** [comment] 2017-03-09 07:33
As mentioned, we want to set it up locally  to, see how its implemented, debug any issues and add functionality if required..

Thanks for the help, much appreciated. !!!

**Comment by nuwang** [comment] 2017-03-09 09:06
No worries and thanks for testing this out on Windows. Let us know if you run into any more issues.

**Closed by nuwang** 2017-03-09 09:06 UTC
