### ISSUE TITLE
[aws provider] moto library not available!

### ISSUE THREAD

**Issue by vjcitn** [gvlproject/cloudbridge#87] opened 2017-09-28 00:54 UTC
following the AWS set at http://cloudbridge.readthedocs.io/en/latest/getting_started.html

with
image_id = 'ami-2d39803a'  # Ubuntu 14.04 (HVM)

are there other setup steps required?

**Comment by nuwang** [comment] 2017-09-28 02:41
Thanks for reporting this. It's caused by a print statement when it should have been a log statement, and has since been fixed: https://github.com/gvlproject/cloudbridge/blob/master/cloudbridge/cloud/providers/aws/provider.py#L12

You can safely ignore this - it only comes up when you have a non dev-mode installation of cloudbridge.

**Comment by vjcitn** [comment] 2017-09-28 04:08
Thanks -- I was impatient -- it takes a while for the demonstration commands

print(provider.compute.images.list())

print(provider.security.security_groups.list())

print(provider.block_store.snapshots.list())

print(provider.object_store.list())


to return... I took the message to indicate an error state and killed the
script.

**Comment by nuwang** [comment] 2017-09-28 04:15
compute.images.list() is particularly slow, because it doesn't filter images by default. We are thinking of optimising that to only list images owned by the current user by default. It should probably not be the first command to try out in the getting started guide so we'll remove it. The other commands should finish reasonably quickly though. Thanks for the useful feedback.

**Comment by nuwang** [comment] 2017-09-28 15:15
Documentation fixed in commit: https://github.com/gvlproject/cloudbridge/commit/940fc7504d4bee75180816e70f6f67d7f608402c#diff-9bc8bf6e8d9db020cefce1fbc0426795R72

**Closed by nuwang** 2017-09-28 15:15 UTC
Labels: bug
